### ISSUE TITLE
svg.js 3.0.13 angular 8.0

### ISSUE THREAD

**Issue by PiotrFr** [svgdotjs/svg.js#1011]
After upgrade from svg.js 3.0.12 to 3.0.13 I get

```
ERROR in node_modules/@svgdotjs/svg.filter.js/node_modules/@svgdotjs/svg.js/svg.js.d.ts(1,1): error TS6200: Definitions of the following identifiers conflict with those in another file: BuiltInArray, utils, defaults, easing, regex, namespaces, AttrNumberValue, SVGTypeMapping, SvgType, ClipPathType, TextType, GType, AType, ParentElement, AttrTypeMapping, ElementAlias, AttributeReference, ArrayAlias, Array, Point, PointArray, NumberUnit, Number, NumberAlias, LineCommand, CurveCommand, PathCommand, PathArrayAlias, PathArray, FlipType, ArrayXY, CoordinateXY, MatrixAlias, Matrix, ColorAlias, Color, Box, MorphValueLike, Morphable, ObjectBag, NonMorphable, TransformBag, Ease, Controller, Queue, Timeline, TimeLike, Runner, Animator, ParentTypeAlias, QuerySelector, ParentQueryAlias, ParentQueryMapping, ParentQueryResultMapping, PutInMapping, PutInResultMapping, Dom, ClipPath, Container, Defs, Svg, Symbol, Element, Circle, Ellipse, Stop, Gradient, G, A, Image, PointArrayAlias, Line, Marker, Mask, Path, Pattern, Polyline, Polygon, Rect, Shape, Text, Tspan, TextPath, Use, ViewBoxAlias
node_modules/@svgdotjs/svg.filter.js/node_modules/@svgdotjs/svg.js/svg.js.d.ts(507,9): error TS2717: Subsequent property declarations must have the same type.  Property 'events' must be of type 'EventObject', but here has type 'Object'.
node_modules/@svgdotjs/svg.filter.js/node_modules/@svgdotjs/svg.js/svg.js.d.ts(1006,9): error TS2416: Property 'events' in type 'Dom' is not assignable to the same property in base type 'EventTarget'.
  Type 'Object' is not assignable to type 'EventObject'.
    The 'Object' type is assignable to very few other types. Did you mean to use the 'any' type instead?
      Index signature is missing in type 'Object'.
node_modules/@svgdotjs/svg.filter.js/node_modules/@svgdotjs/svg.js/svg.js.d.ts(1294,11): error TS2420: Class 'Circle' incorrectly implements interface 'CircleMethods'.
  Type 'Circle' is missing the following properties from type 'CircleMethods': delay, filterWith, draggable
node_modules/@svgdotjs/svg.filter.js/node_modules/@svgdotjs/svg.js/svg.js.d.ts(1305,11): error TS2420: Class 'Ellipse' incorrectly implements interface 'CircleMethods'.
  Type 'Ellipse' is missing the following properties from type 'CircleMethods': delay, filterWith, draggable
node_modules/@svgdotjs/svg.js/svg.js.d.ts(5,1): error TS6200: Definitions of the following identifiers conflict with those in another file: BuiltInArray, utils, defaults, easing, regex, namespaces, AttrNumberValue, SVGTypeMapping, SvgType, ClipPathType, TextType, GType, AType, ParentElement, AttrTypeMapping, ElementAlias, AttributeReference, ArrayAlias, Array, Point, PointArray, NumberUnit, Number, NumberAlias, LineCommand, CurveCommand, PathCommand, PathArrayAlias, PathArray, FlipType, ArrayXY, CoordinateXY, MatrixAlias, Matrix, ColorAlias, Color, Box, MorphValueLike, Morphable, ObjectBag, NonMorphable, TransformBag, Ease, Controller, Queue, Timeline, TimeLike, Runner, Animator, ParentTypeAlias, QuerySelector, ParentQueryAlias, ParentQueryMapping, ParentQueryResultMapping, PutInMapping, PutInResultMapping, Dom, ClipPath, Container, Defs, Svg, Symbol, Element, Circle, Ellipse, Stop, Gradient, G, A, Image, PointArrayAlias, Line, Marker, Mask, Path, Pattern, Polyline, Polygon, Rect, Shape, Text, Tspan, TextPath, Use, ViewBoxAlias
node_modules/@svgdotjs/svg.js/svg.js.d.ts(1511,11): error TS2420: Class 'Polyline' incorrectly implements interface 'poly'.
  Property '_array' is missing in type 'Polyline' but required in type 'poly'.
node_modules/@svgdotjs/svg.js/svg.js.d.ts(1526,11): error TS2420: Class 'Polygon' incorrectly implements interface 'poly'.
  Property '_array' is missing in type 'Polygon' but required in type 'poly'.
```

**Comment by Fuzzyma** [comment]
@maxailloud @cmidt-veasna could this be related to your changes?

**Comment by maxailloud** [comment]
Could be related to the bump in Typescript version with Angular 8.

Or because `svg.filter.js` uses an old version of `svg.js` maybe. The first errors are from the plugin.

**Comment by Fuzzyma** [comment]
Could it be because they updated the dom typings in angular 8? svg.filter has the SVGFEDropShadowElement which was missing iin the dom typings before.

But the error suggests that we are redefining a bunch of stuff as if the typings are imported twice

**Comment by PiotrFr** [comment]
With
```
   "@svgdotjs/svg.draggable.js": "^3.0.2",
    "@svgdotjs/svg.filter.js": "^3.0.7",
    "@svgdotjs/svg.js": "^3.0.14",
    "@svgdotjs/svg.panzoom.js": "^2.0.3",
```

is OK
