### ISSUE TITLE
CustomEvent has incorrect type in IE11

### ISSUE THREAD

**Issue by clusterberries** [svgdotjs/svg.js#852]
Hi guys!
When I added svg.js library to my project, I found some issues with CustomEvent in IE11.
The root of this problem is in this code

```
// Add CustomEvent to IE9 and IE10
    if (typeof window.CustomEvent !== 'function') {
        // Code from: https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent
        var CustomEvent = function(event, options) {
            options = options || { bubbles: false, cancelable: false, detail: undefined }
            var e = document.createEvent('CustomEvent')
            e.initCustomEvent(event, options.bubbles, options.cancelable, options.detail)
            return e
        }

        CustomEvent.prototype = window.Event.prototype

        window.CustomEvent = CustomEvent
    }
```

IE11 supports CustomEvent, but it has type 'object', not 'function'. That's why CustomEvent is rewritten by this code. My problem is the following: code `event instanceof window.CustomEvent` returns true even if `event` is not a CustomEvent.

Please change this approach, because it breaks some functionality related to custom events.
Thank you!

**Comment by saivan** [comment]
I currently don't have access to a windows machine with ie11,
and the other maintainers away for a few days.
If you need this fixed, we would welcome a pull request since it seems that you've isolated the issue.
Otherwise we will get to this as soon as we can.

**Comment by clusterberries** [comment]
@saivan I have found a temporary workaround, so it is not critical. Thank you!

**Comment by saivan** [comment]
Thanks @clusterberries we will take a look soon :)

**Comment by Fuzzyma** [comment]
@clusterberries to make this clear: IE11 does not fully support CustomEvent. It is defined, yes. But you cannot construct them. Calling `new CustomEvent('eventname')` will result in `not supported` errors.

I would have been really suprised if you could create a new object out of something that is not a function. For an object to be created you need a constructor function. So only `new function` works but `new object` does not. CustomEvents therefore NEEDS to be a function.

All in all: its correct, that the broken CustomEvent gets replaced by the polyfill. Whats more important is the question: Why is your code not working with the polyfill?

The prototype chain of CustomEvent is setup correctly so `new CustomEvent instance of CostumEvent` returns true as well as  `new CustomEvent instance of Event`.

**Comment by clusterberries** [comment]
@Fuzzyma CustomEvent is an object in IE, but there is an API `document.createEvent` that allows to create a new CustomEvent without using constructor. It is deprecated, but it still can be used in IE, because this browser doesn't provide any alternative API.

The problem is that `event instanceof CustomEvent` also returns `true` even if event is fired by the browser (like MouseEvent, KeyboardEvent and so on), but it should return `false`.

**Comment by clusterberries** [comment]
@Fuzzyma I think the solution is very simple. The problem is that `instanceof` operator checks prototype properties and it is not set correctly in the CustomEvent object. The following code should work:
`CustomEvent.prototype = Object.create(window.Event.prototype)`

**Comment by Fuzzyma** [comment]
Unfortunately we cannot use `Object.create` because its not working in IE9. And I cannot use `new Event`, too.

**Comment by clusterberries** [comment]
@Fuzzyma can we use `document.createEvent()` instead of `new CustomEvent` if it is not a function? I found out that my solution also doesn't work in 100% cases. There is a mess with prototypes and I can't make the polyfill work correctly. Removing the polyfill and using `document.createEvent()` for IE seems to be the simplest solution.

**Comment by clusterberries** [comment]
@Fuzzyma the second solution is to encapsulate the implementation of CreateEvent polyfill, so only inner methods of svg.js will use it and it will not affect other third-party modules or libraries.

**Comment by Fuzzyma** [comment]
Yes actually I think that is the way to go. If you feel like it you can create a PR for it. Otherwise I will do it at some point

**Comment by Fuzzyma** [comment]
Yes the second one. Maybe under the namespace `SVG.CustomEvent`. Atm I am working on 3.0 together with saivan. And whenever I code its for this. Big things incoming ;).
So you are maybe faster^^

**Comment by Fuzzyma** [comment]
I pushed a fix for this problem. Can you please check if that fixes it?

**Comment by clusterberries** [comment]
@Fuzzyma yes, this fix works!
I was overloaded on my work recently, so I didn't have time to create a PR. Thank you so much!

**Comment by Fuzzyma** [comment]
Cool. Glad to hear that it fixes it. Its already released with 2.6.5 :)
